--Item definition for selling stuff, if the item is not here the default price will be Shop.defaultPrice 
-- and broken price will be Shop.defaultPriceBroken

-- If a item has a sell price equal to 0 it won't show up in the ShopUI window
Shop.defaultPrice = 1 -- Default sell price for items 
Shop.defaultPriceBroken = 0 -- Default sell price for broken items
Shop.SellisBlacklist = false -- Use Shop.Sell as blacklist
Shop.SellisWhitelist = true -- Use Shop.Sell as whitelist
-- If Shop.SellisBlacklist and Shop.SellisWhitelist set to false every item is sellable
Shop.Sell = {
	["Base.KeyRing"] = {blacklisted = true}, --Blacklisted item overrides Shop.SellisWhitelist setting for this item will be price = Shop.defaultPrice
	["Base.Necklace_DogTag"] = { price = 1}, 
	["Base.Necklace_Gold"] = { price = 1}, 
	["Base.Necklace_GoldRuby"] = { price = 2}, 
	["Base.Necklace_GoldDiamond"] = { price = 3}, 
	["Base.Necklace_Silver"] = { price = 1}, 
	["Base.Necklace_SilverSapphire"] = { price = 2}, 
	["Base.Necklace_SilverCrucifix"] = { price = 1}, 
	["Base.Necklace_SilverDiamond"] = { price = 3}, 
	["Base.Necklace_Crucifix"] = { price = 1}, 
	["Base.Necklace_YingYang"] = { price = 1}, 
	["Base.Necklace_Pearl"] = { price = 2}, 
	["Base.NecklaceLong_Gold"] = { price = 1}, 
	["Base.NecklaceLong_GoldDiamond"] = { price = 3}, 
	["Base.NecklaceLong_Silver"] = { price = 1}, 
	["Base.NecklaceLong_SilverEmerald"] = { price = 2}, 
	["Base.NecklaceLong_SilverSapphire"] = { price = 2}, 
	["Base.NecklaceLong_SilverDiamond"] = { price = 3}, 
	["Base.NecklaceLong_Amber"] = { price = 2}, 
	["Base.Necklace_Choker"] = { price = 1}, 
	["Base.Necklace_Choker_Sapphire"] = { price = 2}, 
	["Base.Necklace_Choker_Amber"] = { price = 2}, 
	["Base.Necklace_Choker_Diamond"] = { price = 3}, 
	["Base.NoseRing_Gold"] = { price = 1}, 
	["Base.NoseRing_Silver"] = { price = 1}, 
	["Base.NoseStud_Gold"] = { price = 1}, 
	["Base.NoseStud_Silver"] = { price = 1}, 
	["Base.Earring_LoopLrg_Gold"] = { price = 1}, 
	["Base.Earring_LoopLrg_Silver"] = { price = 1}, 
	["Base.Earring_LoopMed_Silver"] = { price = 1}, 
	["Base.Earring_LoopMed_Gold"] = { price = 1}, 
	["Base.Earring_LoopSmall_Silver_Both"] = { price = 1}, 
	["Base.Earring_LoopSmall_Silver_Top"] = { price = 1}, 
	["Base.Earring_LoopSmall_Gold_Both"] = { price = 1}, 
	["Base.Earring_LoopSmall_Gold_Top"] = { price = 1}, 
	["Base.Earring_Stud_Gold"] = { price = 1}, 
	["Base.Earring_Stud_Silver"] = { price = 1}, 
	["Base.Earring_Stone_Sapphire"] = { price = 2}, 
	["Base.Earring_Stone_Emerald"] = { price = 2}, 
	["Base.Earring_Stone_Ruby"] = { price = 2}, 
	["Base.Earring_Pearl"] = { price = 2}, 
	["Base.Earring_Dangly_Sapphire"] = { price = 2}, 
	["Base.Earring_Dangly_Emerald"] = { price = 2}, 
	["Base.Earring_Dangly_Ruby"] = { price = 2}, 
	["Base.Earring_Dangly_Diamond"] = { price = 3}, 
	["Base.Earring_Dangly_Pearl"] = { price = 2}, 
	["Base.Ring"] = { price = 1},
	["Base.Ring_Right_MiddleFinger_Gold"] = { price = 1}, 
	["Base.Ring_Right_MiddleFinger_Silver"] = { price = 1}, 
	["Base.Ring_Right_MiddleFinger_SilverDiamond"] = { price = 3}, 
	["Base.Ring_Right_MiddleFinger_GoldRuby"] = { price = 2}, 
	["Base.Ring_Right_MiddleFinger_GoldDiamond"] = { price = 3}, 
	["Base.Ring_Left_MiddleFinger_Gold"] = { price = 1}, 
	["Base.Ring_Left_MiddleFinger_Silver"] = { price = 1}, 
	["Base.Ring_Left_MiddleFinger_SilverDiamond"] = { price = 3}, 
	["Base.Ring_Left_MiddleFinger_GoldRuby"] = { price = 2}, 
	["Base.Ring_Left_MiddleFinger_GoldDiamond"] = { price = 3}, 
	["Base.Ring_Right_RingFinger_Gold"] = { price = 1}, 
	["Base.Ring_Right_RingFinger_Silver"] = { price = 1}, 
	["Base.Ring_Right_RingFinger_SilverDiamond"] = { price = 3}, 
	["Base.Ring_Right_RingFinger_GoldRuby"] = { price = 2}, 
	["Base.Ring_Right_RingFinger_GoldDiamond"] = { price = 3}, 
	["Base.Ring_Left_RingFinger_Gold"] = { price = 1}, 
	["Base.Ring_Left_RingFinger_Silver"] = { price = 1}, 
	["Base.Ring_Left_RingFinger_SilverDiamond"] = { price = 3}, 
	["Base.Ring_Left_RingFinger_GoldRuby"] = { price = 2}, 
	["Base.Ring_Left_RingFinger_GoldDiamond"] = { price = 3}, 
	["Base.WeddingRing_Man"] = { price = 1},
	["Base.WeddingRing_Woman"] = { price = 1},
	["Base.WristWatch_Right_ClassicBlack"] = { price = 1}, 
	["Base.WristWatch_Right_ClassicBrown"] = { price = 1}, 
	["Base.WristWatch_Right_ClassicMilitary"] = { price = 1}, 
	["Base.WristWatch_Right_ClassicGold"] = { price = 1}, 
	["Base.WristWatch_Right_DigitalBlack"] = { price = 1}, 
	["Base.WristWatch_Right_DigitalRed"] = { price = 1}, 
	["Base.WristWatch_Right_DigitalDress"] = { price = 1},
	["Base.WristWatch_Left_ClassicBlack"] = { price = 1}, 
	["Base.WristWatch_Left_ClassicBrown"] = { price = 1}, 
	["Base.WristWatch_Left_ClassicMilitary"] = { price = 1}, 
	["Base.WristWatch_Left_ClassicGold"] = { price = 1}, 
	["Base.WristWatch_Left_DigitalBlack"] = { price = 1}, 
	["Base.WristWatch_Left_DigitalRed"] = { price = 1}, 
	["Base.WristWatch_Left_DigitalDress"] = { price = 1},  
	["Base.Bracelet_BangleRightGold"] = { price = 1}, 
	["Base.Bracelet_ChainRightGold"] = { price = 1}, 
	["Base.Bracelet_BangleRightSilver"] = { price = 1}, 
	["Base.Bracelet_ChainRightSilver"] = { price = 1}, 
	["Base.Bracelet_RightFriendshipTINT"] = { price = 1}, 
	["Base.Money"] = { price = 1}, 
	["Base.Glasses_Aviators"] = { price = 1},
	["Base.Glasses_Normal"] = { price = 1},
	["Base.Glasses_Reading"] = { price = 1},
	["Base.Glasses"] = { price = 1},
	["Base.Glasses_SafetyGoggles"] = { price = 1},
	["Base.Glasses_Shooting"] = { price = 1},
	["Base.Glasses_SkiGoggles"] = { price = 1},
	["Base.Glasses_Sun"] = { price = 1},
	["Base.Glasses_SwimmingGoggles"] = { price = 1},
	["Base.Glasses_Eyepatch_Left"] = { price = 1},
	["Base.BellyButton_DangleGold"] = { price = 1},
	["Base.BellyButton_DangleGoldRuby"] = { price = 2},
	["Base.BellyButton_DangleSilver"] = { price = 1},
	["Base.BellyButton_DangleSilverDiamond"] = { price = 3},
	["Base.BellyButton_RingGold"] = { price = 1},
	["Base.BellyButton_RingGoldDiamond"] = { price = 3},
	["Base.BellyButton_RingGoldRuby"] = { price = 2},
	["Base.BellyButton_RingSilver"] = { price = 1},
	["Base.BellyButton_RingSilverAmethyst"] = { price = 2},
	["Base.BellyButton_RingSilverDiamond"] = { price = 3},
	["Base.BellyButton_RingSilverRuby"] = { price = 2},
	["Base.BellyButton_StudGold"] = { price = 1},
	["Base.BellyButton_StudGoldDiamond"] = { price = 3},
	["Base.BellyButton_StudSilver"] = { price = 1},
	["Base.BellyButton_StudSilverDiamond"] = { price = 3},
	["Base.CreditCard"] = { price = 1 , specialCoin = true },
}